services:
  limesurvey:
    image: ghcr.io/sistemica/limesurvey-docker:latest
    restart: always
    depends_on:
      - db
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=limesurvey
      - DB_USERNAME=limesurvey
      - DB_PASSWORD=limesurvey_password
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=my_secure_password
      - ADMIN_NAME=Administrator
      - ADMIN_EMAIL=admin@example.com
      # URL configuration
      - BASE_URL=
      - PUBLIC_URL=http://localhost:8009
      - URL_FORMAT=path
      - SHOW_SCRIPT_NAME=false
    volumes:
      - limesurvey-data:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=limesurvey
      - MYSQL_USER=limesurvey
      - MYSQL_PASSWORD=limesurvey_password
    volumes:
      - db-data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - "8009:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - limesurvey-data:/var/www/html
    depends_on:
      - limesurvey

volumes:
  limesurvey-data:
  db-data:
