name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:
    inputs:
      version:
        description: 'LimeSurvey version (e.g. 6.12.1+250317)'
        required: true
        type: string
      sha256_checksum:
        description: 'SHA256 checksum for the version'
        required: true
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch' }}
            type=raw,value=${{ github.event.inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' }}
            type=sha,format=short,enable=${{ github.event_name != 'workflow_dispatch' }}

      - name: Prepare build arguments
        id: build_args
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            echo "sha256_checksum=${{ github.event.inputs.sha256_checksum }}" >> $GITHUB_OUTPUT
          else
            # Using the version from Dockerfile when not manually specified
            VERSION=$(grep -m 1 "ARG version=" Dockerfile | cut -d'"' -f2)
            SHA256=$(grep -m 1 "ARG sha256_checksum=" Dockerfile | cut -d'"' -f2)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "sha256_checksum=$SHA256" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            version=${{ steps.build_args.outputs.version }}
            sha256_checksum=${{ steps.build_args.outputs.sha256_checksum }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update version in Dockerfile
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        run: |
          sed -i "s/ARG version=\".*\"/ARG version=\"${{ github.event.inputs.version }}\"/" Dockerfile
          sed -i "s/ARG sha256_checksum=\".*\"/ARG sha256_checksum=\"${{ github.event.inputs.sha256_checksum }}\"/" Dockerfile
          
      - name: Commit and push changes
        if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update LimeSurvey version to ${{ github.event.inputs.version }} [skip ci]"
          file_pattern: 'Dockerfile'
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
